import { next } from "@pc/config/eslint/next";

export default [
  ...next({ tsconfigRootDir: import.meta.dirname }),
  {
    // Generated by the shadcn CLI and kept close to upstream so `shadcn add` updates stay clean.
    // Stylistic rules are relaxed here; type safety rules (no-any, unsafe-*) still apply.
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
    },
  },
  {
    // next/og renders with Satori, which only understands plain <img>.
    files: ["src/lib/og.tsx", "src/app/apple-icon.tsx"],
    rules: { "@next/next/no-img-element": "off" },
  },
];
